### PR TITLE
more python 2-3 support

### PR DESCRIPTION
**Pull request by k-funk**
resolves https://github.com/centralniak/cmsplugin_gallery/issues/39

### CODE REVIEW

**Comment by k-funk** [comment]
Looks like tests have been failing for a while :(

**Comment by vinitkumar** [comment]
@k-funk I will look into it today and merge your PR too. It has been crazy few weeks at work so didn't find much time to spend on it.

Thanks for your patience.

**Comment by k-funk** [comment]
Thanks! looking forward to the 1.0.2 (or whatever version # you choose)

**Comment by vinitkumar** [comment]
@k-funk It's live at https://github.com/centralniak/cmsplugin_gallery/releases/tag/v1.1.4

It also has some changes for filer so did a minor version bump.

**Pull request merged**
