### PR TITLE
upgrade migrations to 1.8 style and bump version

### PR DESCRIPTION
**Pull request by vinitkumar**

### CODE REVIEW

**Comment by centralniak** [comment]
Although I no longer support nor use this library I am happy to merge it. Appreciate your work :-)

Perhaps you'd be interested in maintenance of this library?

**Comment by centralniak** [comment]
I will push to pypi later.

**Comment by vinitkumar** [comment]
@centralniak Yes, I would love to maintain this library. We use it in production for our apps. My github username is @vinitkumar. Maybe you can give me commit rights to the repo.

**Comment by centralniak** [comment]
Awesome. I'll get in touch via e-mail.

**Pull request merged**
